version: "3"

services:
  app:
    container_name: pokemon_translation_server
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /pokemon_translation
    ports:
      - 5000:5000
    env_file:
      - .env
