version: "3"

services:
  app:
    image: mcr.microsoft.com/devcontainers/python:0-3.11
    tty: true
    working_dir: /pokemon_translation
    ports:
      - 5000:5000
    env_file:
      - ../.env
    volumes:
      - ..:/pokemon_translation:delegated
