version: "3"

services:
  app:
    image: mcr.microsoft.com/devcontainers/python:0-3.11
    tty: true
    working_dir: /pokemon_translation
    environment:
      PYTHONPATH: $PYTHONPATH:/pokemon_translation/pokemon_translation
    volumes:
      - ..:/pokemon_translation:delegated
